apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "training-microservice-chart.name" . }}-monitor
  labels:
    app: {{ include "training-microservice-chart.name" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ template "training-microservice-chart.name" . }}
  endpoints:
  - port: {{ .Values.service.app.labels.app }}-port
    targetPort: {{ index .Values.service.app.ports 0 "targetPort" }}
    path: /actuator/prometheus
    interval: 15s
