apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-microservice-deployment
  labels:
    name: training-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      name: training-microservice
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: training-microservice
    spec:
      containers:
        - image: elendilearner/microservice-test:v2
          name: training-microservice-container
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            timeoutSeconds: 10
          env:
            - name: MICROSERVICE_PORT
              value: "8000"
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
      restartPolicy: Always
