{
 "title": "common",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latency POST",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "quantile(0.5, rate(http_server_requests_seconds_sum{job=\"training-microservice-service\", method=\"POST\", status=\"201\", uri=\"/api/v1/user\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "quantile(0.95, rate(http_server_requests_seconds_sum{job=\"training-microservice-service\", method=\"POST\", status=\"201\", uri=\"/api/v1/user\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "quantile(0.99, rate(http_server_requests_seconds_sum{job=\"training-microservice-service\", method=\"POST\", status=\"201\", uri=\"/api/v1/user\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(rate(http_server_requests_seconds_sum{job=\"training-microservice-service\", method=\"POST\", status=\"201\", uri=\"/api/v1/user\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency GET",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "quantile(0.5, rate(http_server_requests_seconds_sum{job=\"training-microservice-service\", method=\"GET\", status=\"200\", uri=\"/api/v1/user/{userId}\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "quantile(0.95, rate(http_server_requests_seconds_sum{job=\"training-microservice-service\", method=\"GET\", status=\"200\", uri=\"/api/v1/user/{userId}\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "quantile(0.99, rate(http_server_requests_seconds_sum{job=\"training-microservice-service\", method=\"GET\", status=\"200\", uri=\"/api/v1/user/{userId}\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(rate(http_server_requests_seconds_sum{job=\"training-microservice-service\", method=\"GET\", status=\"200\", uri=\"/api/v1/user/{userId}\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency PUT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "quantile(0.5, rate(http_server_requests_seconds_sum{job=\"training-microservice-service\", method=\"PUT\", status=\"200\", uri=\"/api/v1/user/{userId}\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "quantile(0.95, rate(http_server_requests_seconds_sum{job=\"training-microservice-service\", method=\"PUT\", status=\"200\", uri=\"/api/v1/user/{userId}\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "quantile(0.99, rate(http_server_requests_seconds_sum{job=\"training-microservice-service\", method=\"PUT\", status=\"200\", uri=\"/api/v1/user/{userId}\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(rate(http_server_requests_seconds_sum{job=\"training-microservice-service\", method=\"PUT\", status=\"200\", uri=\"/api/v1/user/{userId}\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency DELETE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "quantile(0.5, rate(http_server_requests_seconds_sum{job=\"training-microservice-service\", method=\"DELETE\", status=\"204\", uri=\"/api/v1/user/{userId}\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "quantile(0.95, rate(http_server_requests_seconds_sum{job=\"training-microservice-service\", method=\"DELETE\", status=\"204\", uri=\"/api/v1/user/{userId}\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "quantile(0.99, rate(http_server_requests_seconds_sum{job=\"training-microservice-service\", method=\"DELETE\", status=\"204\", uri=\"/api/v1/user/{userId}\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(rate(http_server_requests_seconds_sum{job=\"training-microservice-service\", method=\"DELETE\", status=\"204\", uri=\"/api/v1/user/{userId}\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS POST",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"training-microservice-service\", method=\"POST\", status=\"201\", uri=\"/api/v1/user\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS GET",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"training-microservice-service\", method=\"GET\", status=\"200\", uri=\"/api/v1/user/{userId}\"}[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS PUT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"training-microservice-service\", method=\"PUT\", status=\"200\", uri=\"/api/v1/user/{userId}\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS DELETE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"training-microservice-service\", method=\"DELETE\", status=\"204\", uri=\"/api/v1/user/{userId}\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate POST",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"training-microservice-service\", method=\"POST\", status=\"500\", uri=\"/api/v1/user\"}[5m])) / sum(rate(http_server_requests_seconds_count{job=\"training-microservice-service\", method=\"POST\", status=\"201\", uri=\"/api/v1/user\"}[5m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate GET",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"training-microservice-service\", method=\"GET\", status=\"500\", uri=\"/api/v1/user/{userId}\"}[5m])) / sum(rate(http_server_requests_seconds_count{job=\"training-microservice-service\", method=\"GET\", status=\"200\", uri=\"/api/v1/user/{userId}\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate PUT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"training-microservice-service\", method=\"PUT\", status=\"500\", uri=\"/api/v1/user/{userId}\"}[5m])) / sum(rate(http_server_requests_seconds_count{job=\"training-microservice-service\", method=\"PUT\", status=\"200\", uri=\"/api/v1/user/{userId}\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate DELETE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"training-microservice-service\", method=\"DELETE\", status=\"500\", uri=\"/api/v1/user/{userId}\"}[5m])) / sum(rate(http_server_requests_seconds_count{job=\"training-microservice-service\", method=\"DELETE\", status=\"204\", uri=\"/api/v1/user/{userId}\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "memory_usage_byte",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=\"training-microservice-container\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "текущуя загрузка CPU в реальном времени",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"training-microservice-container\"}[60m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}