{
 "title": "ingress common",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latency 0.5",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(nginx_ingress_controller_request_duration_seconds_bucket{job=\"nginx-ingress-microk8s\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 0.99",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(nginx_ingress_controller_request_duration_seconds_bucket{job=\"nginx-ingress-microk8s\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "rate(nginx_ingress_controller_requests{job=\"nginx-ingress-microk8s\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 0.95",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(nginx_ingress_controller_request_duration_seconds_bucket{job=\"nginx-ingress-microk8s\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency max",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 9, "y": 11 },
   "targets": [
    {
     "expr": "max(rate(nginx_ingress_controller_request_duration_seconds_bucket{job=\"nginx-ingress-microk8s\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=\"500\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}