{{- if .Values.ingress.enabled }}
{{- $fullname := include "training-microservice-chart.fullname" . }}
{{- $serviceName := .Values.service.app.name }}

{{- if .Values.ingress.commonIngress.paths }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullname }}-common
spec:
  ingressClassName: "{{ .Values.ingress.class }}"
  rules:
    - host: {{ .Values.ingress.commonIngress.host }}
      http:
        paths:
          {{- range .Values.ingress.commonIngress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: 80
          {{- end }}
{{- end }}

---

{{- if .Values.ingress.specificIngress.paths }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullname }}-specific
  annotations:
    {{- toYaml .Values.ingress.specificIngress.annotations | nindent 4 }}
spec:
  ingressClassName: "{{ .Values.ingress.class }}"
  rules:
    - host: {{ .Values.ingress.specificIngress.host }}
      http:
        paths:
          {{- range .Values.ingress.specificIngress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: 80
          {{- end }}
{{- end }}

---

{{- if .Values.ingress.externalIngress.paths }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-external
spec:
  ingressClassName: "{{ .Values.ingress.class }}"
  rules:
    - http:
        paths:
          {{- range .Values.ingress.externalIngress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: 80
          {{- end }} 
{{- end }}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-external
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: "{{ .Values.ingress.class }}"
  rules:
  - http:
      paths:
      - path: /prometheus/(.*)
        pathType: Prefix
        backend:
          service:
            name: prometheus-kube-prometheus-prometheus
            port:
              number: 9090

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-external
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: "{{ .Values.ingress.class }}"
  rules:
  - http:
      paths:
      - path: /grafana(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: prometheus-grafana
            port:
              number: 80


{{- end }}
