apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-ingress-controller
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      name: nginx-ingress-microk8s
  namespaceSelector:
    matchNames:
      - ingress
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
