apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "training-microservice-chart.name" . }}-monitor
  labels:
    app: {{ include "training-microservice-chart.name" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      name: {{ .Values.service.app.selector }}
  endpoints:
    - port: http
      targetPort: {{ index .Values.service.app.ports 0 "targetPort" }}
      path: /actuator/prometheus
      interval: 15s
