apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "training-microservice-chart.name" . }}-monitor
  labels:
    app: {{ include "training-microservice-chart.name" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      name: {{ .Values.service.metrics.labels.app }}
  endpoints:
    - port: metrics
      targetPort: 8000
      path: /actuator/prometheus
      interval: 15s
